// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDz22uQadZDM9yq8Ee7F5iorgIDmMW1Lg',
    appId: '1:161738553298:web:ec52ffac59511fcb3bfa0b',
    messagingSenderId: '161738553298',
    projectId: 'nandi-ott',
    authDomain: 'nandi-ott.firebaseapp.com',
    storageBucket: 'nandi-ott.firebasestorage.app',
    measurementId: 'G-WC8F45DQC4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANGW_RoDyjqxEPGp_al3aVNC72I2SgkCA',
    appId: '1:161738553298:android:eba1b865a317716e3bfa0b',
    messagingSenderId: '161738553298',
    projectId: 'nandi-ott',
    storageBucket: 'nandi-ott.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7E5VR4abUK0k4LjyA8ylmjYBxVbNwHG4',
    appId: '1:161738553298:ios:b49491314e6f6e4e3bfa0b',
    messagingSenderId: '161738553298',
    projectId: 'nandi-ott',
    storageBucket: 'nandi-ott.firebasestorage.app',
    iosBundleId: 'com.example.nandiottFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7E5VR4abUK0k4LjyA8ylmjYBxVbNwHG4',
    appId: '1:161738553298:ios:b49491314e6f6e4e3bfa0b',
    messagingSenderId: '161738553298',
    projectId: 'nandi-ott',
    storageBucket: 'nandi-ott.firebasestorage.app',
    iosBundleId: 'com.example.nandiottFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDz22uQadZDM9yq8Ee7F5iorgIDmMW1Lg',
    appId: '1:161738553298:web:d2931bc154c4b72b3bfa0b',
    messagingSenderId: '161738553298',
    projectId: 'nandi-ott',
    authDomain: 'nandi-ott.firebaseapp.com',
    storageBucket: 'nandi-ott.firebasestorage.app',
    measurementId: 'G-CKJC0J7CJR',
  );
}
